spring:
  application:
    name: projet_PF2A

  datasource:
    url: jdbc:postgresql://localhost:5433/PF2A_db
    username: postgres
    password: imane

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true